### ISSUE TITLE
couldn't install hms

### ISSUE THREAD

**Issue by Myfanwy** [krlmlr/hms#11]
Hi,

when I ran `devtools::install_github('krlmlr/hms')`, I got the following readout:

`Downloading GitHub repo krlmlr/hms@master
from URL https://api.github.com/repos/krlmlr/hms/zipball/master
Installing hms
Downloading GitHub repo jimhester/covr@v2
from URL https://api.github.com/repos/jimhester/covr/zipball/v2
Error: Could not find build tools necessary to build covr`

I went to his repo page, but I'm not really sure where to start to build covr.  Any help would be greatly appreciated, thanks!

**Comment by krlmlr** [comment]
@jimhester: Why is devtools attempting to grab a "remote" package that is listed in the Suggests?

**Comment by krlmlr** [comment]
Thanks. Could you please try

```
devtools::install_github("krlmlr/hms@feature/11-covr")
```

If you confirm this works, I'll merge, and installation without the `@` suffix will work.

**Comment by Myfanwy** [comment]
@jimhester @krlmlr ok, thanks!  Will try.  I was also running an old version of devtools - but got the same error message after package update.

**Comment by Myfanwy** [comment]
`devtools::install_github("krlmlr/hms@feature/11-covr")` worked!

**Comment by krlmlr** [comment]
Just out of curiosity -- does the error also occur with the bleeding-edge version of devtools?

**Comment by Myfanwy** [comment]
is the bleeding edge version `devtools::install_github("hadley/devtools")` ?  Because if so, I just tried to run that and got the same error I did with `covr`:

```Downloading GitHub repo hadley/devtools@master
from URL https://api.github.com/repos/hadley/devtools/zipball/master
Error: Could not find build tools necessary to build devtools```

**Comment by Myfanwy** [comment]
must be my XCode...?

**Comment by krlmlr** [comment]
Got it sorted out: It's fixed in https://github.com/hadley/devtools/pull/1067, not merged yet. About time ;-)

I can confirm that this version of devtools doesn't attempt installing covr.

**Comment by jimhester** [comment]
FWIW covr v2 has been merged to master and released to CRAN.
